[package]
name = "rustlib"
version = "0.1.0"

[dependencies]
libR-sys = "0.1.1"
rapi = "0.1.0"
neo4j = { path = "neo4j" }

[lib]
name = "rustlib"
crate-type = ["staticlib","rlib"]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
