[package]
name = "neo4j"
version = "0.1.0"
authors = ["Lee Bousfield <ljbousfield@gmail.com>"]
build = "build.rs"

[dependencies]
libR-sys = "0.1.2"
rapi = "0.1.0"
errno = "0.2"

[build-dependencies]
bindgen = "0.53.2"
